spring:
  datasource:
    url: ${JDBC_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 2
  flyway:
    locations: classpath:db/migration/common
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  file:
    name: ${APP_LOG_FILE_LOCATION:./build}/app.log
  logback:
    rollingpolicy:
      # Log files are rotated daily, keep the last 50 days of logs
      max-history: 50

app:
  version: ${version}

---

spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/raspberry_pi_spring_boot_spike}
    username: ${DATABASE_USER:local-user}
    password: ${DATABASE_PASSWORD:local-password}
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/dev
  exposed:
    show-sql: true

app:
  environment: local


---

spring:
  config:
    activate:
      on-profile: raspberrypi

app:
  environment: raspberrypi

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    # IntelliJ shows an error here claiming that the class is not on the path
    # This is because it is only brought in with testImplementation in an effort
    # to keep our jar as lightweight as possible
    driver-class-name: org.h2.Driver
    username: sa
    password: password

app:
  environment: test