spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  exposed:
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  file:
    name: ${APP_LOG_FILE_LOCATION:./build}/app.log

app:
  version: ${version}
